imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@GeneralBundle/Resources/config/services.yml" }
    - { resource: "@PrincipalBundle/Resources/config/services.yml" }

easy_admin:
    entities:
        - GeneralBundle\Entity\Actividades
        - GeneralBundle\Entity\Alicuotas
        - GeneralBundle\Entity\Autoridades
        - GeneralBundle\Entity\Banners
        - GeneralBundle\Entity\Categoriasnoticias
        - GeneralBundle\Entity\Coeficientesinmo
        - GeneralBundle\Entity\Contactos
        - GeneralBundle\Entity\ContribuyenteAuditorias
        - GeneralBundle\Entity\Contribuyentes
        - GeneralBundle\Entity\CuentaAuditorias
        - GeneralBundle\Entity\Cuentascontribuyentes
        - GeneralBundle\Entity\Cuentasmovimientos
        - GeneralBundle\Entity\Cumplimientofiscal
        - GeneralBundle\Entity\Cumplimientos
        - GeneralBundle\Entity\DdjjDetalles
        - GeneralBundle\Entity\DdjjMovimientos
        - GeneralBundle\Entity\Ddjjs
        - GeneralBundle\Entity\DdjjsEstados
        - GeneralBundle\Entity\Departamentos
        - GeneralBundle\Entity\Descartardeuda
        - GeneralBundle\Entity\Destinatarios
        - GeneralBundle\Entity\Estadoscuentas
        - GeneralBundle\Entity\FailedJobs
        - GeneralBundle\Entity\Fechas
        - GeneralBundle\Entity\HistorialCajas
        - GeneralBundle\Entity\Legislaciones
        - GeneralBundle\Entity\LibreDeudas
        - GeneralBundle\Entity\Localidades
        - GeneralBundle\Entity\MailsDdjjsVencidas
        - GeneralBundle\Entity\MatriculasFme
        - GeneralBundle\Entity\Migrations
        - GeneralBundle\Entity\Modalesinicio
        - GeneralBundle\Entity\Noticias
        - GeneralBundle\Entity\Objetosimponibles
        - GeneralBundle\Entity\PasswordResets
        - GeneralBundle\Entity\Periodos
        - GeneralBundle\Entity\Periodosinmo
        - GeneralBundle\Entity\Permissions
        - GeneralBundle\Entity\PersonalAccessTokens
        - GeneralBundle\Entity\Personas
        - GeneralBundle\Entity\Propietarios
        - GeneralBundle\Entity\Provincias
        - GeneralBundle\Entity\Referencias
        - GeneralBundle\Entity\Representantes
        - GeneralBundle\Entity\Roles
        - GeneralBundle\Entity\Servicios
        - GeneralBundle\Entity\Sessions
        - GeneralBundle\Entity\Solicitudarchivo
        - GeneralBundle\Entity\Solicitudpersona
        - GeneralBundle\Entity\Solicitudrepresentante
        - GeneralBundle\Entity\Solicitudsucursal
        - GeneralBundle\Entity\Sucursales
        - GeneralBundle\Entity\TipoFondos
        - GeneralBundle\Entity\TipoPersonaJuridica
        - GeneralBundle\Entity\TipoPropietarios
        - GeneralBundle\Entity\Tiposimpuestos
        - GeneralBundle\Entity\Tiposlegislaciones
        - GeneralBundle\Entity\TiposMatriculas
        - GeneralBundle\Entity\Tiposmovimientos
        - GeneralBundle\Entity\Tipospersonas
        - GeneralBundle\Entity\Tramites
        - GeneralBundle\Entity\Users

    site_name: 'SysFray'

tetranz_select2_entity:
    minimum_input_length: 2
    page_limit: 8
    allow_clear: true
    delay: 500
    language: es
    cache: false
    cache_timeout: 0
    scroll: true


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    #DIRECTORIO DE ARCHIVOS PDF
    archivos: '%kernel.project_dir%/web/uploads/archivos'
    plantillas: '%kernel.project_dir%/web/uploads/plantillas'
    actualizar_tabla: '%kernel.project_dir%/web/uploads/actualizar_tabla'
    carpeta_xls: '%kernel.project_dir%/web/uploads/archivos_xls'
    items_comprar: '%kernel.project_dir%/web/uploads/items_comprar'
    carpeta_img: '%kernel.project_dir%/web/uploads/archivos_img'
    institucion: 'SECRETARIA DE COMPRAS'

framework:
    #esi: ~
    translator: #{ fallbacks: ['%locale%'], logging: false }
        enabled: true
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    templating:
            engines: ['twig']
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
    #form: 
    #Añade themas de bootstrap para formularios Vertical(activado) u Orizontal (#)
     #   resources: ['bootstrap_3_layout.html.twig']
        #resources: ['bootstrap_3_horizontal_layout.html.twig']
    globals:
        # NOMBRE DE LA INSTITUCION  
        appInstitucion: '%institucion%'
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool: { type: memory }

# Assetic Configuration 
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:                                 
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:                                        
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'     # boostrap3 pagination controls template                                    
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template                                
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
