<?php

namespace Siarme\DocumentoBundle\Repository;

/**
 * CompartirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompartirRepository extends \Doctrine\ORM\EntityRepository
{
	 # BUSCA COMPARTIDOS POR USUARIOS
     /**
     *  @param string $id y $slug El id de DepartamentoRm
     *  
     *  @return array
     */
    public function  findByUsuario($tipoId, $tipo, $usuarioId)
    {
         $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT c
             FROM DocumentoBundle:Compartir c  
             JOIN c.usuarioEnvia ue
             JOIN c.usuarioRecive ur
             WHERE c.tipoId = :id 
             AND c.tipo = :tipo
             AND ( ue.id= :usuarioId OR ur.id= :usuarioId)'
            );

        $consulta->setParameter('id', $tipoId);
        // si estado de expediente es True => INICIADO si False=> CONCLUIDO
        // si estadoTurnoCitacion de tramite es True => con turno  si False=> sin turno
        $consulta->setParameter('tipo', $tipo);
       // $consulta->setParameter('estadoTyC', true);
        $consulta->setParameter('usuarioId', $usuarioId);
                
        return  $consulta->getResult();  
    }
}
