<?php

namespace Siarme\DocumentoBundle\Repository;

use Doctrine\ORM\EntityRepository;
//use Sirme\DocumentoBundle\Entity\TipoDocumento;

/**
 * DocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoRepository extends EntityRepository
{
 # BUSCA LOS DOCUMENTOS CON TRAMITE EN TRANSITO POR DEPARTAMENTO
   # RM Y SLUG DEL DOCUMENTO
     /**
     *  @param string $id y $slug El id de DepartamentoRm
     *  
     *  @return array
     */
    public function  findByDepartamentoRmAndSlug($id, $slug)
    {
         $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT doc
             FROM DocumentoBundle:Documento doc  
             JOIN doc.tramite t
             JOIN t.departamentoRm d
             WHERE d.id = :id AND t.estado = :estado AND doc.slug = :slug'
            );

        $consulta->setParameter('id', $id);
        // si estado de expediente es True => INICIADO si False=> CONCLUIDO
        // si estadoTurnoCitacion de tramite es True => con turno  si False=> sin turno
        $consulta->setParameter('estado', true);
       // $consulta->setParameter('estadoTyC', true);
        $consulta->setParameter('slug', $slug);
                
        return  $consulta->getResult();  
    }

    # BUSCA LOS DOCUMENTOS CON TRAMITE EN TRANSITO POR DEPARTAMENTO
   # RM Y SLUG DEL DOCUMENTO
     /**
     *  @param string $id y $slug El id de DepartamentoRm
     *  
     *  @return array
     */
    public function  findByExpedienteAndSlug($id, $slug)
    {
         $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT doc
             FROM DocumentoBundle:Documento doc  
             JOIN doc.tramite t
             JOIN t.expediente e
             WHERE e.id = :id AND doc.slug = :slug 
             ORDER BY doc.id DESC'
            );

        $consulta->setParameter('id', $id);
        $consulta->setParameter('slug', $slug);
        $consulta->setMaxResults(1);   
        return $consulta->getOneOrNullResult();
    }
}
