<?php

namespace Siarme\AusentismoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenteRepository extends EntityRepository
{

	 # BUSCA LOS AGENTES RECIENTES
     /**
     *  @return array
     */
    public function  findAgentes()
    {
         $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT a
             FROM AusentismoBundle:Agente a
             ORDER BY a.fechaModifica DESC'
            );

        $consulta->setMaxResults(100);
                
        return  $consulta->getResult();  
    }



}
