<?php

namespace Siarme\AusentismoBundle\Repository;

/**
 * GrupoRubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRubroRepository extends \Doctrine\ORM\EntityRepository
{
}
