<?php

namespace Siarme\AusentismoBundle\Repository;

/**
 * ItemProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemOfertaRepository extends \Doctrine\ORM\EntityRepository
{

     # Busca todos los Items y los ordena por numero y precio
     /**
     *  @return array
     */
    public function  findAllItem($tramite, $slug )
    {
         $em = $this->getEntityManager();
         if ($slug == "tramite_proceso") {
                $dql = 'SELECT i
                FROM AusentismoBundle:ItemOferta i
                WHERE i.proceso = :id 
                AND i.estado = :estado
                AND i.calidad IN (:calidades)
                ORDER BY i.numero  ASC , i.precio ASC';
                $query = $em->createQuery($dql);
                $query->setParameter('id', $tramite);
                $query->setParameter('estado', true);
                $query->setParameter('calidades', ["2","3"]);

         } else {

                $dql = 'SELECT i
                FROM AusentismoBundle:ItemOferta i
                WHERE i.oferta = :id AND i.estado = :estado
                ORDER BY i.numero  ASC, i.precio ASC';
                $query = $em->createQuery($dql);
                $query->setParameter('id', $tramite);
                $query->setParameter('estado', true);
         }



                
        return  $query->getResult();  
    }
    

     # Busca todos los Items y los ordena por numero y mayor puntaje
     /**
     *  @return array
     */
    public function  findAllByMayorPuntaje($tramite)
    {
         $em = $this->getEntityManager();
       
                $dql = 'SELECT i
                FROM AusentismoBundle:ItemOferta i
                WHERE i.proceso = :id 
                AND i.estado = :estado
                AND i.calidad IN (:calidades)
                ORDER BY i.numero  ASC , i.pFTotal   DESC';

          $query = $em->createQuery($dql);
          $query->setParameter('id', $tramite);
          $query->setParameter('estado', true);
          $query->setParameter('calidades', ["2","3"]);
                
        return  $query->getResult();  
    }
}
