<?php

namespace Siarme\AusentismoBundle\Repository;

/**
 * ItemPedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPedidoRepository extends \Doctrine\ORM\EntityRepository
{
    
}
