<?php

namespace Siarme\AusentismoBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCatalogoRepository extends \Doctrine\ORM\EntityRepository
{
}
