<?php

namespace Siarme\AusentismoBundle\Repository;

/**
 * ItemProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
