<?php

namespace Siarme\AusentismoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenciaRepository extends EntityRepository
{
	   # BUSCA LICENCIAS POR ID AGENTE
     /**
     *  @param integer $id del Agente
     *  
     *  @return array
     */
    public function  findByAgente($id)
    {

        $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT l 
            FROM AusentismoBundle:Licencia l  
            JOIN l.agente a
             WHERE a.id = :id AND l.fechaDesde > :fecha
             ORDER BY l.fechaDesde DESC'
            );

        $consulta->setParameter('id', $id);
        // si estado de expediente es True => INICIADO si False=> CONCLUIDO
         $consulta->setParameter('fecha', new \DateTime('now - 365 days'));
         
                
        return  $consulta->getResult();  
    }



       # COMPRUEBA SI EXISTE LA LICENCIA DEL AGENTE POR  FECHA DESDE
     /**
     *  @param integer $id del Agente
     *  @param date $fechaDesde la Licencia
     *  
     *  @return array
     */
    public function  findByAgenteFecha($id, $fecha)
    {
        $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT l 
            FROM AusentismoBundle:Licencia l  
            JOIN l.agente a
             WHERE (l.fechaDesde <= :fecha
             AND l.fechaHasta >= :fecha ) 
             AND a.id = :id
             ORDER BY l.fechaDesde DESC'
            );

        $consulta->setParameter('id', $id);
        // si estado de expediente es True => INICIADO si False=> CONCLUIDO
         $consulta->setParameter('fecha', $fecha);
          //dump($consulta->getResult());
         // exit();

        return  $consulta->getResult();  
    }


        # COMPRUEBA SI EXISTE LA LICENCIA DEL AGENTE POR  FECHA DESDE
     /**
     *  @param integer $id del Agente
     *  @param date $fechaDesde la Licencia
     *  @param date $fechaHasta la Licencia
     *  
     *  @return array
     */
    public function  findByAgentePeriodo($id, $fechaDesde, $fechaHasta)
    {
        $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT l 
            FROM AusentismoBundle:Licencia l  
            JOIN l.agente a
             WHERE a.id = :id 
             AND l.fechaDesde > :fechaDesde
             AND l.fechaHasta < :fechaHasta

             ORDER BY l.fechaDesde DESC'
            );

        $consulta->setParameter('id', $id);
        // si estado de expediente es True => INICIADO si False=> CONCLUIDO
         $consulta->setParameter('fechaDesde', $fechaDesde);
         $consulta->setParameter('fechaHasta', $fechaHasta);
        //   dump($consulta->getResult());
         //  exit();
        return  $consulta->getResult();  
    }
}
