<?php

namespace Siarme\AusentismoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismoRepository extends EntityRepository
{
    /**
     * Encuentra los  TRAMITE con TAREAS relacionados con el USUARIO
     * 
     * 
     */
  public function findByExpedienteReparticion($id)
  {
        $em = $this->getEntityManager();
        $dql = 'SELECT t..estado AS estado, o.organismo AS organismo, COUNT(dt.id) AS cantidad
                FROM AusentismoBundle:Organismo o 
                JOIN o.cargo c
                JOIN c.agente a
                JOIN a.expediente e
                INNER JOIN e.datoAt dt
                WHERE dt.fechaAt >= :fec1 
                AND dt.fechaAt <= :fec2
                GROUP BY  o, dt.estado';
     
        $query = $em->createQuery($dql);
        $query->setParameter('fec1', $fechaDesde);
        $query->setParameter('fec2', $fechaHasta);
        $informe = $query->getResult();
        return $informe;
  }

}
