<?php

namespace Siarme\AusentismoBundle\Repository;

/**
 * SafRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SafRepository extends \Doctrine\ORM\EntityRepository
{
}
