<?php

namespace Siarme\UsuarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	
 /**
     * Encuentra el los Expedientes con Citacion
     *
     *  @param string $rolename El id de DepartamentoRm
     *  @return 
     */
    public function  finByNombreRol($rolename)
    {
        $em = $this->getEntityManager();

         $consulta = $em->createQuery(
            'SELECT u
             FROM UsuarioBundle:Usuario u 
             JOIN u.rol r  
             WHERE r.roleName = :nombrerol'
            );

        $consulta->setParameter('nombrerol', $rolename);
                
        return  $consulta->getResult();  
    }
}
