<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * BandejaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandejaRepository extends \Doctrine\ORM\EntityRepository
{
}
