<?php

namespace Siarme\ExpedienteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClasificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionRepository extends EntityRepository
{
	 /**
     * 
     * @param $clasificacion
     * @return  $tipoDocumento.
     * 
     */
    public  function getByClasificacion($clasificacion)
    {
        $em = $this->getEntityManager();
       
        $clasificacion = $em->getRepository('ExpedienteBundle:Clasificacion')->findOneByClasificacion($clasificacion);
        

        return $clasificacion;
    }
}
