<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * DatoATRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatoATRepository extends \Doctrine\ORM\EntityRepository
{
}
