<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * EstadoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoTramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
