<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * MarcoLegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcoLegalRepository extends \Doctrine\ORM\EntityRepository
{
}
