<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * Encuentra los  TRAMITE con TAREAS relacionados con el USUARIO
     * 
     * 
     */
  public function findByExpedienteReparticion($id)
  {
        $em = $this->getEntityManager();

        $consulta = $em->createQuery(
                 'SELECT e
                        FROM ExpedienteBundle:Expediente e 
                        JOIN e.movimiento mov
                        WHERE mov.departamentoRm= :id
                        ');
        $consulta->setParameter('id', $id);

        $expedientes = $consulta->getResult();           
                 
        return $expedientes;
    }
}
