<?php

namespace Siarme\ExpedienteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTramiteRepository extends EntityRepository
{

    /**
     * Encuentra los  TipoTramite de un Expediente
     * 
     */
  public function findByExpediente($expediente)
  {
        $em = $this->getEntityManager();

        $consulta = $em->createQuery(
                 'SELECT tt, t
                        FROM ExpedienteBundle:TipoTramite tt 
                        JOIN tt.tramite t
                        WHERE t.expediente = :id'
                    );
        $consulta->setParameter('id', $expediente->getId());         
                 
        return $consulta->getResult(); 
    }

    /**
     * Encuentra los  TipoTramite de un Organismo
     * 
     */
  public function findByOrganismo($organismo, $anio = null)
  {
     if (empty($anio)) {
            $date = new \Datetime();
            $anio = $date->format("Y");
        }

        $fechaDesde = $anio."/01/01";
        $fechaDesde = new \DateTime($fechaDesde);
        $fechaDesde = $fechaDesde->format('Y/m/d');

        $fechaHasta = $anio."/12/31";
        $fechaHasta = new \DateTime($fechaHasta);
        $fechaHasta = $fechaHasta->format('Y/m/d');

        $em = $this->getEntityManager();

        $consulta = $em->createQuery(
                 'SELECT tt, t, e 
                        FROM ExpedienteBundle:TipoTramite tt 
                        JOIN tt.tramite t
                        JOIN t.expediente e
                        JOIN e.tramite tra
                        WHERE tra.fechaDestino >= :fechaDesde 
                        AND tra.fechaDestino <= :fechaHasta
                        AND tra.organismoOrigen = :id'
                    );
        $consulta->setParameter('id', $organismo->getId())
                 ->setParameter('fechaDesde', $fechaDesde)
                 ->setParameter('fechaHasta', $fechaHasta);         
                 
        return $consulta->getResult(); 
    }

      /**
     * Encuentra los  TipoTramite de un Agente
     * 
     */
    public function findByAgente($agente, $anio)
    {
        if (empty($anio)) {
            $date = new \Datetime();
            $anio = $date->format("Y");
        }

        $fechaDesde = $anio."/01/01";
        $fechaDesde = new \DateTime($fechaDesde);
        $fechaDesde = $fechaDesde->format('Y/m/d');

        $fechaHasta = $anio."/12/31";
        $fechaHasta = new \DateTime($fechaHasta);
        $fechaHasta = $fechaHasta->format('Y/m/d');

        $em = $this->getEntityManager();

        $consulta = $em->createQuery(
                 'SELECT tt, t, ta
                        FROM ExpedienteBundle:TipoTramite tt 
                        JOIN tt.tramite t
                        JOIN t.tarea ta
                        JOIN ta.usuario u
                        WHERE u.agente = :id
                        AND t.fechaDestino >= :fechaDesde 
                        AND t.fechaDestino <= :fechaHasta'
                    );
        $consulta->setParameter('id', $agente->getId())
                 ->setParameter('fechaDesde', $fechaDesde)
                 ->setParameter('fechaHasta', $fechaHasta);         
                 
        return $consulta->getResult(); 
    }
    
    /**
     * Encuentra los  TipoTramite de un Agente
     * 
     */
    public function findByProveedor($proveedor, $anio)
    {
        if (empty($anio)) {
            $date = new \Datetime();
            $anio = $date->format("Y");
        }

        $fechaDesde = $anio."/01/01";
        $fechaDesde = new \DateTime($fechaDesde);
        $fechaDesde = $fechaDesde->format('Y/m/d');

        $fechaHasta = $anio."/12/31";
        $fechaHasta = new \DateTime($fechaHasta);
        $fechaHasta = $fechaHasta->format('Y/m/d');

        $em = $this->getEntityManager();

        $consulta = $em->createQuery(
                 'SELECT tt, t
                        FROM ExpedienteBundle:TipoTramite tt 
                        JOIN tt.tramite t
                        WHERE t.proveedor = :id
                        AND t.fechaDestino >= :fechaDesde 
                        AND t.fechaDestino <= :fechaHasta'
                    );
        $consulta->setParameter('id', $proveedor->getId())
                 ->setParameter('fechaDesde', $fechaDesde)
                 ->setParameter('fechaHasta', $fechaHasta);         
                 
        return $consulta->getResult(); 
    }
}
