<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * TipoBandejaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoBandejaRepository extends \Doctrine\ORM\EntityRepository
{
}
