<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * TipoExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoExpedienteRepository extends \Doctrine\ORM\EntityRepository
{
}
