<?php

namespace Siarme\ExpedienteBundle\Repository;

/**
 * TipoProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
