<?php

namespace Siarme\GeneralBundle\Repository;

/**
 * ArrayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrayRepository extends \Doctrine\ORM\EntityRepository
{
}
